version: '3.8'
services:
#  api-auth:
#    build: .
#    ports:
#      - "5002:5002"
#    environment:
#      - FLASK_ENV=development
#      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@auth-db:5432/authdb
#    depends_on:
#      - auth-db
#    restart: always

  auth-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authdb
    ports:
      - "5434:5432"
    volumes:
      - auth_pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  auth_pgdata: